bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Tanya Sarkin Jain
  description: A variant caller for PacBio long read sequencing - also can be used
    for PureTarget panel analysis, and quantification of repeat expansions
  force: false
  is_nfcore: true
  name: pacvar
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
