contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pacvar channel"
    url: https://nfcore.slack.com/channels/pacvar
    about: Discussion about the nf-core/pacvar pipeline
